version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.19

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          command: npm install
      - run:
          command: npm run test:ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: nextjs
